package cn.itcast.entity;
// Generated 2017-6-9 23:56:04 by Hibernate Tools 3.5.0.Final

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private int aid;
	private String apassword;

	public Admin() {
	}

	public Admin(int aid) {
		this.aid = aid;
	}

	public Admin(int aid, String apassword) {
		this.aid = aid;
		this.apassword = apassword;
	}

	public int getAid() {
		return this.aid;
	}

	public void setAid(int aid) {
		this.aid = aid;
	}

	public String getApassword() {
		return this.apassword;
	}

	public void setApassword(String apassword) {
		this.apassword = apassword;
	}

}
