package cn.itcast.entity;
// Generated 2017-6-9 23:56:04 by Hibernate Tools 3.5.0.Final

/**
 * Class generated by hbm2java
 */
public class Class implements java.io.Serializable {

	private int classid;
	private String classname;

	public Class() {
	}

	public Class(int classid) {
		this.classid = classid;
	}

	public Class(int classid, String classname) {
		this.classid = classid;
		this.classname = classname;
	}

	public int getClassid() {
		return this.classid;
	}

	public void setClassid(int classid) {
		this.classid = classid;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

}
