package cn.itcast.entity;
// Generated 2017-6-9 23:56:04 by Hibernate Tools 3.5.0.Final

/**
 * ClassCourse generated by hbm2java
 */
public class ClassCourse implements java.io.Serializable {

	private int cno;
	private String coursertime;
	private String courseaddr;
	private String classname;
	private String coursedata;

	public ClassCourse() {
	}

	public ClassCourse(int cno, String coursertime, String courseaddr, String classname) {
		this.cno = cno;
		this.coursertime = coursertime;
		this.courseaddr = courseaddr;
		this.classname = classname;
	}

	public ClassCourse(int cno, String coursertime, String courseaddr, String classname, String coursedata) {
		this.cno = cno;
		this.coursertime = coursertime;
		this.courseaddr = courseaddr;
		this.classname = classname;
		this.coursedata = coursedata;
	}

	public int getCno() {
		return this.cno;
	}

	public void setCno(int cno) {
		this.cno = cno;
	}

	public String getCoursertime() {
		return this.coursertime;
	}

	public void setCoursertime(String coursertime) {
		this.coursertime = coursertime;
	}

	public String getCourseaddr() {
		return this.courseaddr;
	}

	public void setCourseaddr(String courseaddr) {
		this.courseaddr = courseaddr;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	public String getCoursedata() {
		return this.coursedata;
	}

	public void setCoursedata(String coursedata) {
		this.coursedata = coursedata;
	}

}
