package cn.itcast.entity;
// Generated 2017-6-9 23:56:04 by Hibernate Tools 3.5.0.Final

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private int cno;
	private String cname;
	private String tname;

	public Course() {
	}

	public Course(int cno) {
		this.cno = cno;
	}

	public Course(int cno, String cname, String tname) {
		this.cno = cno;
		this.cname = cname;
		this.tname = tname;
	}

	public int getCno() {
		return this.cno;
	}

	public void setCno(int cno) {
		this.cno = cno;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

}
