package cn.itcast.entity;
// Generated 2017-6-9 23:56:04 by Hibernate Tools 3.5.0.Final

/**
 * StuClas generated by hbm2java
 */
public class StuClas implements java.io.Serializable {

	private StuClasId id;

	public StuClas() {
	}

	public StuClas(StuClasId id) {
		this.id = id;
	}

	public StuClasId getId() {
		return this.id;
	}

	public void setId(StuClasId id) {
		this.id = id;
	}

}
