package cn.itcast.entity;
// Generated 2017-6-9 23:56:04 by Hibernate Tools 3.5.0.Final

/**
 * StuClasId generated by hbm2java
 */
public class StuClasId implements java.io.Serializable {

	private int sno;
	private int classid;

	public StuClasId() {
	}

	public StuClasId(int sno, int classid) {
		this.sno = sno;
		this.classid = classid;
	}

	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	public int getClassid() {
		return this.classid;
	}

	public void setClassid(int classid) {
		this.classid = classid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StuClasId))
			return false;
		StuClasId castOther = (StuClasId) other;

		return (this.getSno() == castOther.getSno()) && (this.getClassid() == castOther.getClassid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSno();
		result = 37 * result + this.getClassid();
		return result;
	}

}
