package cn.itcast.entity;
// Generated 2017-6-9 23:56:04 by Hibernate Tools 3.5.0.Final

/**
 * TC generated by hbm2java
 */
public class TC implements java.io.Serializable {

	private TCId id;

	public TC() {
	}

	public TC(TCId id) {
		this.id = id;
	}

	public TCId getId() {
		return this.id;
	}

	public void setId(TCId id) {
		this.id = id;
	}

}
