package cn.itcast.entity;
// Generated 2017-6-9 23:56:04 by Hibernate Tools 3.5.0.Final

/**
 * TCId generated by hbm2java
 */
public class TCId implements java.io.Serializable {

	private int cno;
	private String tname;

	public TCId() {
	}

	public TCId(int cno, String tname) {
		this.cno = cno;
		this.tname = tname;
	}

	public int getCno() {
		return this.cno;
	}

	public void setCno(int cno) {
		this.cno = cno;
	}

	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TCId))
			return false;
		TCId castOther = (TCId) other;

		return (this.getCno() == castOther.getCno())
				&& ((this.getTname() == castOther.getTname()) || (this.getTname() != null
						&& castOther.getTname() != null && this.getTname().equals(castOther.getTname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCno();
		result = 37 * result + (getTname() == null ? 0 : this.getTname().hashCode());
		return result;
	}

}
