package cn.itcast.entity;
// Generated 2017-6-9 23:56:04 by Hibernate Tools 3.5.0.Final

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private Integer id;
	private String tname;
	private Integer tnumber;
	private String tpassword;

	public Teacher() {
	}

	public Teacher(String tname, Integer tnumber, String tpassword) {
		this.tname = tname;
		this.tnumber = tnumber;
		this.tpassword = tpassword;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public Integer getTnumber() {
		return this.tnumber;
	}

	public void setTnumber(Integer tnumber) {
		this.tnumber = tnumber;
	}

	public String getTpassword() {
		return this.tpassword;
	}

	public void setTpassword(String tpassword) {
		this.tpassword = tpassword;
	}

}
